export const industries = [
  'Technology',
  'Business',
  'Finance',
  'Marketing',
  'Healthcare',
  'Engineering',
  'Creative',
  'Science',
  'Education',
  'Retail & Sales',
  'Manufacturing',
  'Hospitality & Tourism',
  'Legal',
  'Agriculture',
  'Construction',
  'Government & Public Sector',
  'Media & Communications',
  'Transportation & Logistics',
  'Energy & Utilities',
  'Non-Profit',
  'Other',
] as const;